name: build-packages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build ${{ matrix.arch_name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - goarch: amd64
            arch_name: x86_64
          - goarch: arm64
            arch_name: aarch64

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Load Version
        run: |
          version=$(cat VERSION)
          echo "version=$version" >> $GITHUB_ENV

      - name: Build daed Binary
        env:
          GOOS: linux
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
        run: |
          mkdir -p bin/outputs
          go build -v -trimpath -ldflags "-s -w" -o bin/outputs/daed-${{ matrix.arch_name }} .

      - name: Upload packages
        uses: ncipollo/release-action@v1
        with:
          name: daed_${{ env.version }}
          tag: daed_${{ env.version }}
          allowUpdates: true
          commit: main
          token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          replacesArtifacts: true
          artifacts: "bin/outputs/daed-*"
