name: Build Packages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - VERSION

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: x86_64
            goarch: amd64
          - arch: arm64
            goarch: arm64

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Load VERSION
        run: |
          version=$(grep PKG_VERSION VERSION | cut -d '=' -f2 | tr -d ':')
          wing_sha=$(grep WING_VERSION VERSION | sed 's/.*wing-//')
          core_sha=$(grep CORE_VERSION VERSION | sed 's/.*core-//')
          echo "version=$version" >> $GITHUB_ENV
          echo "WING_SHA=$wing_sha" >> $GITHUB_ENV
          echo "CORE_SHA=$core_sha" >> $GITHUB_ENV

      - name: Checkout dae-wing (commit SHA)
        uses: actions/checkout@v4
        with:
          repository: daeuniverse/dae-wing
          ref: ${{ env.WING_SHA }}
          path: wing-src
          fetch-depth: 0

      - name: Replace core with your olicesx version (SHA)
        run: |
          cd wing-src
          go mod edit -replace github.com/daeuniverse/dae=github.com/olicesx/dae@${CORE_SHA}
          go mod tidy

      - name: Build daed
        run: |
          cd wing-src
          mkdir -p ../bin
          GOOS=linux GOARCH=${{ matrix.goarch }} CGO_ENABLED=0 \
            go build -v -trimpath -ldflags "-s -w" \
            -o ../bin/daed-${{ matrix.arch }} \
            ./cmd/dae-wing

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: daed-${{ matrix.arch }}
          path: bin/daed-${{ matrix.arch }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: daed-${{ env.version }}-${{ env.CORE_SHA }}
          name: daed-${{ env.version }}-${{ env.CORE_SHA }}
          files: bin/*
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
