name: Build Web

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Fetch Upstream Commits
        id: upstream
        run: |
          DAED_FULL=$(curl -s https://api.github.com/repos/daeuniverse/daed/commits/main | jq -r '.sha')
          WING_FULL=$(curl -s https://api.github.com/repos/daeuniverse/dae-wing/commits/main | jq -r '.sha')
          CORE_FULL=$(curl -s https://api.github.com/repos/olicesx/dae/commits/optimize/code-quality-fixes | jq -r '.sha')

          DAED_SHA=$(echo "$DAED_FULL" | cut -c1-7)
          WING_SHA=$(echo "$WING_FULL" | cut -c1-7)
          CORE_SHA=$(echo "$CORE_FULL" | cut -c1-7)

          echo "DAED_SHA=$DAED_SHA" >> $GITHUB_ENV
          echo "WING_SHA=$WING_SHA" >> $GITHUB_ENV
          echo "CORE_SHA=$CORE_SHA" >> $GITHUB_ENV

          echo "DAED_FULL=$DAED_FULL" >> $GITHUB_ENV
          echo "WING_FULL=$WING_FULL" >> $GITHUB_ENV
          echo "CORE_FULL=$CORE_FULL" >> $GITHUB_ENV

      - name: Generate VERSION file
        run: |
          PKG_VERSION=$(date "+%Y.%m.%d")

          echo "PKG_VERSION:=$PKG_VERSION" > VERSION
          echo "DAED_VERSION:=daed-${DAED_SHA}" >> VERSION
          echo "WING_VERSION:=wing-${WING_SHA}" >> VERSION
          echo "CORE_VERSION:=core-${CORE_SHA}" >> VERSION

          echo "version=${PKG_VERSION}-${DAED_SHA}" >> $GITHUB_ENV

      - name: Commit VERSION
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add VERSION
          git commit -m "Update upstream: $version" || echo "No changes"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          branch: main
