name: Build daed binary

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build ${{ matrix.arch }}-${{ matrix.sdk }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_generic    
          - x86_64
        sdk:
          - openwrt-24.10

    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Init build dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo swapoff -a
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install clang llvm npm jq
          sudo npm install -g pnpm n
          sudo n stable
          if [ -d "daed/Makefile" ]; then
            latest_commit=$(grep "DAED_VERSION:=daed-" daed/Makefile | sed 's/.*daed-//' | head -n 1)
            echo "version=$latest_commit" >> "$GITHUB_ENV"
          else
            echo "version=$(date +%Y%m%d)" >> "$GITHUB_ENV"
          fi

      - name: Building daed via SDK
        uses: sbwml/openwrt-gh-action-sdk@go1.26
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.sdk }}
          FEEDNAME: packages_ci
          PACKAGES: daed
          NO_REFRESH_CHECK: true
          V: s

      - name: Extract binary
        run: |
          mkdir -p ./release_bin
          TARGET_BIN=$(find sdk/build_dir/ -type f -name "daed" -executable | grep -v "host" | head -n 1)
          if [ -n "$TARGET_BIN" ]; then
            cp "$TARGET_BIN" ./release_bin/daed-${{ matrix.arch }}
          else
            IPK_PATH=$(find bin/packages/${{ matrix.arch }}/ -name "daed_*.ipk" | head -n 1)
            tar -xOf "$IPK_PATH" data.tar.gz | tar -xzOf - ./usr/bin/daed > ./release_bin/daed-${{ matrix.arch }}
          fi
          chmod +x ./release_bin/daed-${{ matrix.arch }}

      - name: Upload
        uses: ncipollo/release-action@v1
        with:
          name: daed_${{ env.version }}
          allowUpdates: true
          tag: daed_${{ env.version }}
          commit: main
          token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          replacesArtifacts: true
          artifacts: "./release_bin/daed-*"
